In [1]:
import os
import pandas as pd

In [2]:
nr = pd.read_pickle(os.path.join('res', 'pickles', 'drug_fp.pkl'))

In [3]:
bank = pd.read_pickle(os.path.join('res', 'pickles', 'drugbank_fp.pkl'))
bank = bank.dropna()

In [5]:
nr['Morgan2FP'].map(type).unique()

array([<class 'numpy.ndarray'>], dtype=object)

In [6]:
#lenseries = bank['ConnInvariants'].map(len)
bank['Morgan2FP'].map(type).unique()

array([<class 'numpy.ndarray'>], dtype=object)

In [7]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2896 entries, 5 to 14995
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Molecule        2896 non-null   object
 1   atc_code_3      2896 non-null   object
 2   CID             2896 non-null   float64
 3   atc_code_#      2896 non-null   int32
 4   FeatInvariants  2896 non-null   object
 5   ConnInvariants  2896 non-null   object
 6   Morgan2FP       2896 non-null   object
 7   MACCSKeys       2896 non-null   object
 8   AtomPairFP      2896 non-null   object
 9   TopTorFP        2896 non-null   object
 10  AvalonFP        2896 non-null   object
 11  PubchemFP       2896 non-null   object
 12  CactvsFP        2896 non-null   object
dtypes: float64(1), int32(1), object(11)
memory usage: 305.4+ KB

In [8]:
sorted(bank['atc_code_#'].unique())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [16]:
bank.groupby('atc_code_#').count()

,Molecule,atc_code_3,CID,FeatInvariants,ConnInvariants,Morgan2FP,MACCSKeys,AtomPairFP,TopTorFP,AvalonFP,PubchemFP,CactvsFP
atc_code_#,,,,,,,,,,,,
0,338,338,338,338,338,338,338,338,338,338,338,338
1,95,95,95,95,95,95,95,95,95,95,95,95
2,340,340,340,340,340,340,340,340,340,340,340,340
3,174,174,174,174,174,174,174,174,174,174,174,174
4,164,164,164,164,164,164,164,164,164,164,164,164
5,41,41,41,41,41,41,41,41,41,41,41,41
6,314,314,314,314,314,314,314,314,314,314,314,314
7,259,259,259,259,259,259,259,259,259,259,259,259
8,140,140,140,140,140,140,140,140,140,140,140,140
9,491,491,491,491,491,491,491,491,491,491,491,491
10,96,96,96,96,96,96,96,96,96,96,96,96
11,200,200,200,200,200,200,200,200,200,200,200,200
12,101,101,101,101,101,101,101,101,101,101,101,101
13,143,143,143,143,143,143,143,143,143,143,143,143